### ISSUE TITLE
which paper to reference? 

### ISSUE THREAD

**Issue by gumanchang** [gpapadis/DLMatchers#1]

**Comment by gpapadis** [comment]
Thanks for reaching out! For the time being, please refer to:
Konstantinos Nikoletos, George Papadakis, Manolis Koubarakis. pyJedAI: a Lightsaber for Link Discovery. ISWC 2022 (to appear as a demo).
Kind regards,
George

**Comment by gpapadis** [comment]
Btw, here is the link to the system: https://github.com/AI-team-UoA/pyJedAI

**Comment by gumanchang** [comment]
thanks.
