### ISSUE TITLE
You may miss "Entity Resolution with Hierarchical Graph Attention Networks"

### ISSUE THREAD

**Issue by tshu-w** [gpapadis/DLMatchers#3]
I would like to see the results of HierGAT.

**Comment by gpapadis** [comment]
Hi! Thank you for the recommendation. We are already working on it!

**Comment by tshu-w** [comment]
I would also like to respectfully express my hope to see the results of a new benchmark using Sparkly (which is essentially BM25) as a replacement for DeepBlocker, as it performs better in the blocking stage and allows for a better comparison with [our work](https://github.com/tshu-w/LLM4EM).

This is an easy-to-use Python implementation of BM25 https://github.com/AmenRa/retriv.
